// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCbhqt0AmKM_Zulb4nQILAfUT9QfoO56xQ',
    appId: '1:911443768062:web:60cdb40dfbc1b17fcc6baf',
    messagingSenderId: '911443768062',
    projectId: 'tapme-a598a',
    authDomain: 'tapme-a598a.firebaseapp.com',
    storageBucket: 'tapme-a598a.appspot.com',
    measurementId: 'G-M8EXLFPNXD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCWDlOeUuXU317DSj47TAfPO3ZCrbYg2_8',
    appId: '1:911443768062:android:722482b06797711dcc6baf',
    messagingSenderId: '911443768062',
    projectId: 'tapme-a598a',
    storageBucket: 'tapme-a598a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB3n1vwSba2SVUJitA0nQSCFLYHk_HqJ_Q',
    appId: '1:911443768062:ios:8b3ceee14764c76acc6baf',
    messagingSenderId: '911443768062',
    projectId: 'tapme-a598a',
    storageBucket: 'tapme-a598a.appspot.com',
    iosClientId: '911443768062-d7q6ai4cvums99a8l3i746kug727a1ho.apps.googleusercontent.com',
    iosBundleId: 'com.example.tapmetoremember',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB3n1vwSba2SVUJitA0nQSCFLYHk_HqJ_Q',
    appId: '1:911443768062:ios:8b3ceee14764c76acc6baf',
    messagingSenderId: '911443768062',
    projectId: 'tapme-a598a',
    storageBucket: 'tapme-a598a.appspot.com',
    iosClientId: '911443768062-d7q6ai4cvums99a8l3i746kug727a1ho.apps.googleusercontent.com',
    iosBundleId: 'com.example.tapmetoremember',
  );
}
